parameters:
    allies_extendedmagento.importexport.data_converter.order.class:         Allies\Bundle\ExtendedMagentoBundle\ImportExport\Converter\OrderDataConverter
    allies_extendedmagento.importexport.data_converter.order_item.class:    Allies\Bundle\ExtendedMagentoBundle\ImportExport\Converter\OrderItemDataConverter
    allies_extendedmagento.importexport.data_converter.cart.class:          Allies\Bundle\ExtendedMagentoBundle\ImportExport\Converter\CartDataConverter
    allies_extendedmagento.importexport.data_converter.cart_item.class:     Allies\Bundle\ExtendedMagentoBundle\ImportExport\Converter\CartItemDataConverter
    
services:
    allies_extendedmagento.importexport.data_converter.order_item:
        class: %allies_extendedmagento.importexport.data_converter.order_item.class%
        parent: oro_magento.importexport.data_converter.order_item
        
    oro_magento.importexport.data_converter.order:
        class: %allies_extendedmagento.importexport.data_converter.order.class%
        calls:
            - [addNodeDataConverter, ['shipping_address', @oro_magento.importexport.data_converter.order_address]]
            - [addNodeDataConverter, ['billing_address', @oro_magento.importexport.data_converter.order_address]]
            - [addNodeDataConverter, ['items', @allies_extendedmagento.importexport.data_converter.order_item, true]]
            
    allies_extendedmagento.importexport.data_converter.cart_item:
        class: %allies_extendedmagento.importexport.data_converter.cart_item.class%
        parent: oro_magento.importexport.data_converter.cartitem
        
    oro_magento.importexport.data_converter.cart:
        class:  %allies_extendedmagento.importexport.data_converter.cart.class%
        calls:
            - [addNodeDataConverter, ['shipping_address', "@oro_magento.importexport.data_converter.cart_address"]]
            - [addNodeDataConverter, ['billing_address', "@oro_magento.importexport.data_converter.cart_address"]]
            - [addNodeDataConverter, ['items', @allies_extendedmagento.importexport.data_converter.cart_item, true]]
