parameters:
    allies_extendedmagento.importexport.data_converter.order_item.class:    Allies\Bundle\ExtendedMagentoBundle\ImportExport\Converter\OrderItemDataConverter
    
services:
    allies_extendedmagento.importexport.data_converter.order_item:
        class: %allies_extendedmagento.importexport.data_converter.order_item.class%
        parent: oro_magento.importexport.data_converter.order_item
        
    oro_magento.importexport.data_converter.order:
        class: %oro_magento.importexport.data_converter.order.class%
        calls:
            - [addNodeDataConverter, ['shipping_address', @oro_magento.importexport.data_converter.order_address]]
            - [addNodeDataConverter, ['billing_address', @oro_magento.importexport.data_converter.order_address]]
            - [addNodeDataConverter, ['items', @allies_extendedmagento.importexport.data_converter.order_item, true]]
